In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from csv import reader

In [2]:
data= pd.read_csv('CCMLEmployeeData.csv')

In [ ]:
movie_name= input("Enter movie name: ")

In [3]:
data.head()

Name           Domain          Event1          Event2
0      Bryan Brock       Management            Jobs      Hackathons
1  Joseph Sullivan           Coding  Certifications        Webinars
2    Sherri Dawson         Security     Internships           Fests
3  Dustin Ferguson         Hardware    Competitions        Webinars
4      Kayla Young  Web Development           Expos  Certifications

In [4]:
data['Domain'].value_counts()

Other                      11
Security                   11
Cloud Computing            11
Coding                     10
Python                     10
Management                 10
Blockchain                  9
Mobile Applications         9
Java                        9
IoT                         9
Networking                  9
Finance                     9
C++                         8
C                           8
Development Processes       8
Web Development             7
Machine Learning            7
Higher Education            7
JavaScript                  5
Software Architecture       5
Data Science                4
Hardware                    4
Artificial Intelligence     3
Name: Domain, dtype: int64

In [5]:
string = 'Get a System Administration courses from PurpleHat today.'

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    183 non-null    object
 1   Domain  183 non-null    object
 2   Event1  183 non-null    object
 3   Event2  183 non-null    object
dtypes: object(4)
memory usage: 5.8+ KB


In [15]:
words = string.split()
words

['Get',
 'a',
 'System',
 'Administration',
 'courses',
 'from',
 'PurpleHat',
 'today.']

In [16]:
new_dataset = data.applymap(str.lower)

In [9]:
Domain = new_dataset['Domain'].unique()
Domain

array(['management', 'coding', 'security', 'hardware', 'web development',
       'higher education', 'iot', 'java', 'artificial intelligence',
       'python', 'finance', 'mobile applications', 'c++',
       'software architecture', 'other', 'c', 'cloud computing',
       'networking', 'javascript', 'machine learning', 'blockchain',
       'development processes', 'data science'], dtype=object)

In [10]:

Events = new_dataset['Event1'].unique()
Events

array(['jobs', 'certifications', 'internships', 'competitions', 'expos',
       'workshops', 'trainings', 'seminars', 'hackathons', 'fests',
       'talks', 'webinars', 'courses'], dtype=object)

In [11]:
new_dataset

Name                 Domain          Event1          Event2
0           bryan brock             management            jobs      hackathons
1       joseph sullivan                 coding  certifications        webinars
2         sherri dawson               security     internships           fests
3       dustin ferguson               hardware    competitions        webinars
4           kayla young        web development           expos  certifications
..                  ...                    ...             ...             ...
178      katelyn barnes                 coding         courses        webinars
179        gabriel cruz                  other           talks           fests
180  christina williams  software architecture           talks           fests
181      william turner  development processes       trainings        seminars
182          damon lane                      c        seminars     internships

[183 rows x 4 columns]

In [14]:

for item in words:
    if item.lower() in Domain:
        index = np.where(Domain == item.lower())
        print('Domain: ',Domain[index])
    if item.lower() in Events:
        index = np.where(Events == item.lower())
        print('Event: ',Events[index])

Event:  ['courses']


In [5]:
data.columns

Index(['Name', 'Domain', 'Event1', 'Event2'], dtype='object')

In [6]:
features=['Domain','Event1','Event2']

In [7]:
for f in features:
    data[f] = data[f].fillna('')

In [8]:
data['Domain'] = data['Domain'].fillna('')
data['description'] = data['Domain'] + data['Event1']+data['Event2']
data['description'] = data['description'].fillna('')

In [9]:
data


Name                 Domain          Event1  \
0           Bryan Brock             Management            Jobs   
1       Joseph Sullivan                 Coding  Certifications   
2         Sherri Dawson               Security     Internships   
3       Dustin Ferguson               Hardware    Competitions   
4           Kayla Young        Web Development           Expos   
..                  ...                    ...             ...   
178      Katelyn Barnes                 Coding         Courses   
179        Gabriel Cruz                  Other           Talks   
180  Christina Williams  Software Architecture           Talks   
181      William Turner  Development Processes       Trainings   
182          Damon Lane                      C        Seminars   

             Event2                             description  
0        Hackathons                ManagementJobsHackathons  
1          Webinars            CodingCertificationsWebinars  
2             Fests                SecurityInternshipsFests  
3          Webinars            HardwareCompetitionsWebinars  
4    Certifications      Web DevelopmentExposCertifications  
..              ...                                     ...  
178        Webinars                   CodingCoursesWebinars  
179           Fests                         OtherTalksFests  
180           Fests         Software ArchitectureTalksFests  
181        Seminars  Development ProcessesTrainingsSeminars  
182     Internships                    CSeminarsInternships  

[183 rows x 5 columns]

In [10]:
data['Domain'].value_counts()

Other                      11
Security                   11
Cloud Computing            11
Coding                     10
Python                     10
Management                 10
Blockchain                  9
Mobile Applications         9
Java                        9
IoT                         9
Networking                  9
Finance                     9
C++                         8
C                           8
Development Processes       8
Web Development             7
Machine Learning            7
Higher Education            7
JavaScript                  5
Software Architecture       5
Data Science                4
Hardware                    4
Artificial Intelligence     3
Name: Domain, dtype: int64

In [11]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(data['description'])

In [12]:
tfidf_matrix.shape


(183, 241)

In [13]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [14]:

cosine_sim[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:

data = data.reset_index(drop=True)
titles = data['description']
indices = pd.Series(data.index, index=data['description'])

In [16]:
    indices.dtypes

dtype('int64')

In [17]:
indices

description
ManagementJobsHackathons                    0
CodingCertificationsWebinars                1
SecurityInternshipsFests                    2
HardwareCompetitionsWebinars                3
Web DevelopmentExposCertifications          4
                                         ... 
CodingCoursesWebinars                     178
OtherTalksFests                           179
Software ArchitectureTalksFests           180
Development ProcessesTrainingsSeminars    181
CSeminarsInternships                      182
Length: 183, dtype: int64

In [18]:
def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [20]:
get_recommendations('ManagementJobsHackathons').head(10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
def combineFeatures(row):
    return row['Domain'] + " " + row['Event1'] + " " + row['Event2'] 

data['combineFeatures'] = data.apply(combineFeatures, axis = 1)

In [12]:
data['combineFeatures']

0                    Management Jobs Hackathons
1                Coding Certifications Webinars
2                    Security Internships Fests
3                Hardware Competitions Webinars
4          Web Development Expos Certifications
                         ...                   
178                     Coding Courses Webinars
179                           Other Talks Fests
180           Software Architecture Talks Fests
181    Development Processes Trainings Seminars
182                      C Seminars Internships
Name: combineFeatures, Length: 183, dtype: object

In [13]:
data

Name                 Domain          Event1  \
0           Bryan Brock             Management            Jobs   
1       Joseph Sullivan                 Coding  Certifications   
2         Sherri Dawson               Security     Internships   
3       Dustin Ferguson               Hardware    Competitions   
4           Kayla Young        Web Development           Expos   
..                  ...                    ...             ...   
178      Katelyn Barnes                 Coding         Courses   
179        Gabriel Cruz                  Other           Talks   
180  Christina Williams  Software Architecture           Talks   
181      William Turner  Development Processes       Trainings   
182          Damon Lane                      C        Seminars   

             Event2                           combineFeatures  
0        Hackathons                Management Jobs Hackathons  
1          Webinars            Coding Certifications Webinars  
2             Fests                Security Internships Fests  
3          Webinars            Hardware Competitions Webinars  
4    Certifications      Web Development Expos Certifications  
..              ...                                       ...  
178        Webinars                   Coding Courses Webinars  
179           Fests                         Other Talks Fests  
180           Fests         Software Architecture Talks Fests  
181        Seminars  Development Processes Trainings Seminars  
182     Internships                    C Seminars Internships  

[183 rows x 5 columns]

In [30]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(data['combineFeatures'])
cosine_sim = cosine_similarity(count_matrix,count_matrix)

In [31]:
cosine_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.28867513, 0.        ,
        0.40824829],
       ...,
       [0.        , 0.        , 0.28867513, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.35355339],
       [0.        , 0.        , 0.40824829, ..., 0.        , 0.35355339,
        1.        ]])

In [41]:
cosine_sim[0]

array([1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.        , 0.66666667, 0.        , 0.33333333, 0.66666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.33333333,
       0.        , 0.33333333, 0.        , 0.        , 0.        ,
       0.        , 0.28867513, 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.40824829, 0.        , 0.33333333,
       0.        , 0.33333333, 0.        , 0.        , 0.28867513,
       0.33333333, 0.        , 0.        , 0.        , 0.33333333,
       0.        , 0.28867513, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33333333, 0.66666667, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.33333333, 0.     

In [49]:
data = data.reset_index(drop=True)
indices = pd.Series(data.index, index=data['combineFeatures'])

In [50]:
movie_index = data[data.Event1 == movie_name]["Event1"]
similar_movies =  list(enumerate(cosine_sim[movie_index]))
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [51]:
[print(sorted_similar_movies[x]) for x in range(0)]

[]

In [52]:
data['Domain']=data['Domain'].fillna('')
data['Event1']= data['Event1'].fillna('')
data['Event2']= data['Event2'].fillna('')

data['Domain']= data['Domain'] + data['Event1'] + data['Event2']


In [9]:
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(data['Domain'])

In [11]:
tfidf_matrix.shape

(183, 241)

In [14]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [31]:
cosine_sim[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:

indices = pd.Series(data.index, index=data['Event1'])

In [34]:
indices

Event1
Jobs                0
Certifications      1
Internships         2
Competitions        3
Expos               4
                 ... 
Courses           178
Talks             179
Talks             180
Trainings         181
Seminars          182
Length: 183, dtype: int64

In [57]:
def get_recommendations_userwise(eventname):
    idx = indices[eventname]
    #print (idx)
    sim_scores = list(enumerate(cosine_sim[idx]))
    #print (sim_scores)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    user_indices = [i[0] for i in sim_scores]
    #print (user_indices)
    return user_indices[0:11]

In [63]:
print ("-----Top 10 Similar users with userId: 123------")
get_recommendations_userwise('Programming')

-----Top 10 Similar users with userId: 123------


KeyError: 'Programming'

In [59]:
def get_job_id(usrid_list):
    jobs_userwise = data['Domain'].isin(usrid_list) #
    df1 = pd.DataFrame(data = data[jobs_userwise], columns=['Domain'])
    joblist = df1['Domain'].tolist()
    Job_list = data['Name'].isin(joblist) #[1083186, 516837, 507614, 754917, 686406, 1058896, 335132])
    df_temp = pd.DataFrame(data = data[Job_list], columns=['Name','Domain','Event1','Event2'])
    return df_temp

In [62]:
get_job_id(get_recommendations_userwise(100))

Empty DataFrame
Columns: [Name, Domain, Event1, Event2]
Index: []